# Generated by Django 3.1.1 on 2020-10-02 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_habilidades'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habilidades',
            old_name='habilida',
            new_name='habilidad',
        ),
        migrations.AddField(
            model_name='empleado',
            name='habilidad',
            field=models.ManyToManyField(to='persona.Habilidades'),
        ),
    ]
